services:
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_dataverse
      - POSTGRES_PASSWORD=dvnsecret
      - POSTGRES_USER=dataverse
      - TZ=Asia/Jakarta
    volumes:
      - ./docker-dev-volumes/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  app_be:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-dev-app_be
    ports:
      - 82:3000
    command: "yarn dev"
    volumes:
      - ./app_be:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
  app_fe:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-dev-app_fe
    ports:
      - 83:3000
    command: "yarn dev"
    volumes:
      - ./app_fe:/app
      - /app/node_modules
  solr:
    image: solr:8.8
    environment:
      SOLR_HEAP: 2g
    volumes:
      - ./docker-dev-volumes/solr-data:/opt/solr/server/solr/mycores
  dataverse:
      image: coronawhy/dataverse:5.2.2-cv
      container_name: dataverse
      privileged: true
      ports:
        - "443:443"
        - "4848:4848"
        - "8085:8080"
      environment:
        - "CVM_SERVER_NAME=CESSDA" #Optional
        - "CVM_SERVER_URL=https://vocabularies-dev.cessda.eu/v2/search/vocabularies"
        - "CVM_TSV_SOURCE=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/citation.tsv"
        - "1GIT_CVM_TEMPLATES=https://github.com/Dans-labs/semantic-gateway"
        - "WAR_FILE=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/dataverse-5.2-cv.war"
        - "GIT_BRANCH=v5.2-cvm"
        - "CVM_SQL=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/cv-update.sql"
        - "CVM_CONFIG=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/cv-cessda-keywords.json"
        - "GIT_SOURCE=https://github.com/ekoi/dataverse"
        - "GIT_BRANCH=v5.0-cvm-autocomplete"
        - "LANG=en"
        - "cvManager=http://"
        - "BUNDLEPROPERTIES=Bundle.properties"
        - "ADMIN_EMAIL=admin@localhost"
        - "MAIL_SERVER=mailrelay"
        - "POSTGRES_SERVER=db"
        - "POSTGRES_PORT=5432"
        - "POSTGRES_DATABASE=db_dataverse"
        - "POSTGRES_USER=dataverse"
        - "PGPASSWORD=dvnsecret"
     #   - "POSTGRES_PASSWORD=dv"
        - "SOLR_LOCATION=solr:8983"
        - "TWORAVENS_LOCATION=NOT INSTALLED"
        - "RSERVE_HOST=localhost"
        - "RSERVE_PORT=6311"
        - "RSERVE_USER=rserve"
        - "RSERVE_PASSWORD=rserve"
        - "JVM_OPTS='-Xmx1g -Xms1g -XX:MaxPermSize=2g -XX:PermSize=2g'"
      depends_on:
        - db
        - solr
      volumes:
        - dataverse-data:/usr/local/payara5/glassfish/domains/domain1/autodeploy
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dataverse.loadbalancer.server.port=8080"
volumes:
  database-data:
  solr-data:
  dataverse-data: