# Use the official Node.js image as the base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

COPY app_be/package.json .

RUN yarn install

# Expose the port that the app will run on
EXPOSE 3000
